export default [
  {
    title: "Cerveja enquanto o noivo espera a noiva voltar das compras",
    price: 23,
    image: "/images/cerveja.jpg",
    buyers: 0,
  },
  {
    title: "Rolo de macarrão para a noiva utilizar quando necessário",
    price: 37,
    image: "/images/rolomacarrao.webp",
    buyers: 0,
  },
  {
    title: "Capacete contra rolo de macarrão",
    price: 49,
    image: "/images/capacete.jpg",
    buyers: 0,
  },
  {
    title: "Não deixar faltar um docinho",
    price: 53,
    image: "/images/brigadeiro.jpeg",
    buyers: 0,
  },
  {
    title: "Balança para os noivos não engordarem após o casamento",
    price: 62,
    image: "/images/balanca.webp",
    buyers: 0,
  },
  {
    title: "Bolo de cenoura semanal para a noiva",
    price: 74,
    image: "/images/bolocenoura.webp",
    buyers: 0,
  },
  {
    title: "Garanta o jantar do noivo no 1º dia de casados",
    price: 86,
    image: "/images/pizza.jpg",
    buyers: 0,
  },
  {
    title: "Transfer do aeroporto para casa",
    price: 109,
    image: "/images/transfer.avif",
    buyers: 0,
  },
  {
    title: "Ajuda com o excesso de bagagem",
    price: 110,
    image: "/images/bagagens.webp",
    buyers: 0,
  },
  {
    title: "Massagem relaxante para o noivo depois de ver a conta do casamento",
    price: 126,
    image: "/images/massagem.webp",
    buyers: 0,
  },
  {
    title: "Cota para pagar prejuízos da viagem",
    price: 179,
    image: "/images/aviao.jpg",
    buyers: 0,
  },
  {
    title: "Aluguel de carro popular",
    price: 180,
    image: "/images/carrao.webp",
    buyers: 0,
  },
  {
    title: "Jantar romântico",
    price: 185,
    image: "/images/jantar.avif",
    buyers: 0,
  },
  {
    title: "Cota de reforma do apartamento novo",
    price: 194,
    image: "/images/reforma.jpg",
    buyers: 0,
  },
  {
    title: "Um fone de ouvido para não ouvir o noivo cantando no chuveiro",
    price: 198,
    image: "/images/headset.jpg",
    buyers: 0,
  },
  {
    title: "Noite de fondue",
    price: 214,
    image: "/images/fondue.webp",
    buyers: 0,
  },
  {
    title: "Maleta de pôquer para o noivo jogar e ganhar dos amigos",
    price: 223,
    image: "/images/maleta-poker.jpg",
    buyers: 0,
  },
  {
    title: "Conjunto de malas para a viagem mais especial de nossas vidas",
    price: 245,
    image: "/images/malas.webp",
    buyers: 0,
  },
  {
    title: "Curso de culinária para noivo",
    price: 247,
    image: "/images/culinaria.jpg",
    buyers: 0,
  },
  {
    title: "Curtir todos os passeios e atrações",
    price: 321,
    image: "/images/passeios.jpg",
    buyers: 0,
  },
  {
    title: "Conjunto de sabres de luz para o casal",
    price: 328,
    image: "/images/sabres.webp",
    buyers: 0,
  },
  {
    title: "Coleção de jogos para diversão do noivo e tristeza da noiva",
    price: 367,
    image: "/images/jogos.jpg",
    buyers: 0,
  },
  {
    title: "Academia para os noivos entrarem em forma depois da lua de mel",
    price: 460,
    image: "/images/academia.jpg",
    buyers: 0,
  },
  {
    title: "Saco e luva de boxe para os noivos aliviarem a tensão",
    price: 463,
    image: "/images/boxe.webp",
    buyers: 0,
  },
  {
    title: "Viagem para os noivos visitarem a família",
    price: 674,
    image: "/images/estrada.jpg",
    buyers: 0,
  },
];
